#!/usr/bin/env python3
"""Generate fixed 1-bit Chinese header glyphs for deterministic ESP32 drawing."""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


GLYPH_SIZE = 24
GLYPHS = ("月", "日", "星", "期", "一", "二", "三", "四", "五", "六", "亿")
FONT_PATH = Path(r"C:\Windows\Fonts\Noto Sans SC Bold (TrueType).otf")


def render_glyph(character: str, selected_font: ImageFont.FreeTypeFont) -> Image.Image:
    image = Image.new("1", (GLYPH_SIZE, GLYPH_SIZE), 0)
    draw = ImageDraw.Draw(image)
    bounds = draw.textbbox((0, 0), character, font=selected_font)
    width = bounds[2] - bounds[0]
    height = bounds[3] - bounds[1]
    x = (GLYPH_SIZE - width) // 2 - bounds[0]
    y = (GLYPH_SIZE - height) // 2 - bounds[1]
    draw.text((x, y), character, font=selected_font, fill=1)
    return image


def pack_bitmap(image: Image.Image) -> bytes:
    packed = bytearray()
    pixels = image.load()
    for y in range(GLYPH_SIZE):
        for start_x in range(0, GLYPH_SIZE, 8):
            value = 0
            for bit in range(8):
                if pixels[start_x + bit, y]:
                    value |= 0x80 >> bit
            packed.append(value)
    return bytes(packed)


def cpp_bytes(data: bytes) -> str:
    lines = []
    for start in range(0, len(data), 12):
        chunk = data[start : start + 12]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return "\n".join(lines)


def generate(project_root: Path) -> None:
    if not FONT_PATH.is_file():
        raise FileNotFoundError(f"Chinese font is missing: {FONT_PATH}")
    selected_font = ImageFont.truetype(str(FONT_PATH), GLYPH_SIZE)
    rendered = [render_glyph(character, selected_font) for character in GLYPHS]
    packed = [pack_bitmap(image) for image in rendered]
    bytes_per_glyph = GLYPH_SIZE * GLYPH_SIZE // 8

    header = f'''#pragma once

#include <Arduino.h>

namespace inkdash::header_glyphs {{

constexpr int16_t kHeaderGlyphWidth = {GLYPH_SIZE};
constexpr int16_t kHeaderGlyphHeight = {GLYPH_SIZE};
constexpr size_t kHeaderGlyphBytes = {bytes_per_glyph};

enum GlyphIndex : uint8_t {{
  kMonth = 0,
  kDay = 1,
  kWeek = 2,
  kPeriod = 3,
  kOne = 4,
  kTwo = 5,
  kThree = 6,
  kFour = 7,
  kFive = 8,
  kSix = 9,
  kYi = 10,
  kGlyphCount = 11,
}};

extern const uint8_t kGlyphBitmaps[kGlyphCount][kHeaderGlyphBytes];

}}  // namespace inkdash::header_glyphs
'''

    rows = []
    for character, bitmap in zip(GLYPHS, packed):
        rows.append(f"  // {character}")
        rows.append("  {")
        rows.append(cpp_bytes(bitmap))
        rows.append("  },")
    source = '''// Generated by tools/generate_header_glyphs.py. Do not edit by hand.
#include <Arduino.h>

#include "generated/header_glyphs.h"

namespace inkdash::header_glyphs {

const uint8_t kGlyphBitmaps[kGlyphCount][kHeaderGlyphBytes] PROGMEM = {
''' + "\n".join(rows) + '''
};

}  // namespace inkdash::header_glyphs
'''

    include_path = project_root / "include" / "generated" / "header_glyphs.h"
    source_path = project_root / "src" / "generated" / "header_glyphs.cpp"
    include_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.parent.mkdir(parents=True, exist_ok=True)
    include_path.write_text(header, encoding="utf-8")
    source_path.write_text(source, encoding="utf-8")

    preview = Image.new("RGB", (GLYPH_SIZE * len(GLYPHS), 48), "white")
    for index, (character, bitmap_image) in enumerate(zip(GLYPHS, rendered)):
        preview.paste(
            Image.merge(
                "RGB",
                tuple(bitmap_image.convert("L") for _ in range(3)),
            ),
            (index * GLYPH_SIZE, 0),
        )
        ImageDraw.Draw(preview).text(
            (index * GLYPH_SIZE + GLYPH_SIZE // 2, 46),
            str(index),
            font=ImageFont.truetype(r"C:\Windows\Fonts\arial.ttf", 12),
            fill="black",
            anchor="ms",
        )
    preview_path = project_root / "artifacts" / "header-glyph-preview.png"
    preview_path.parent.mkdir(parents=True, exist_ok=True)
    preview.save(preview_path)
    print(f"generated {len(GLYPHS)} glyphs ({bytes_per_glyph} bytes each)")


if __name__ == "__main__":
    generate(Path(__file__).resolve().parents[1])
