#!/usr/bin/env python3
"""Convert exact 800x480 black/white/red PNGs into verified RLE C++ assets."""

from __future__ import annotations

import argparse
import textwrap
import zlib
from dataclasses import dataclass
from pathlib import Path

from PIL import Image


WIDTH = 800
HEIGHT = 480
PLANE_BYTES = WIDTH * HEIGHT // 8
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
ALLOWED = {WHITE, BLACK, RED}


@dataclass(frozen=True)
class AssetSpec:
    symbol: str
    frame_id: str
    filename: str


ASSETS = (
    AssetSpec("CodexQuota", "codex-quota", "codex-quota.png"),
    AssetSpec("ServerStatus", "server-status", "server-status.png"),
)


def image_to_planes(path: Path) -> tuple[bytes, bytes]:
    image = Image.open(path).convert("RGB")
    if image.size != (WIDTH, HEIGHT):
        raise ValueError(f"{path}: expected {WIDTH}x{HEIGHT}, got {image.size}")

    flattened = (
        image.get_flattened_data()
        if hasattr(image, "get_flattened_data")
        else image.getdata()
    )
    colors = set(flattened)
    unexpected = colors - ALLOWED
    if unexpected:
        sample = sorted(unexpected)[:8]
        raise ValueError(f"{path}: non-tricolor pixels found, e.g. {sample}")

    black = bytearray([0xFF] * PLANE_BYTES)
    red = bytearray([0xFF] * PLANE_BYTES)
    pixels = image.load()
    for y in range(HEIGHT):
        row_offset = y * (WIDTH // 8)
        for x in range(WIDTH):
            color = pixels[x, y]
            if color == WHITE:
                continue
            byte_index = row_offset + x // 8
            bit = 0x80 >> (x % 8)
            if color == BLACK:
                black[byte_index] &= ~bit
            else:
                red[byte_index] &= ~bit
    return bytes(black), bytes(red)


def encode_rle(raw: bytes) -> bytes:
    encoded = bytearray()
    cursor = 0
    while cursor < len(raw):
        value = raw[cursor]
        count = 1
        while cursor + count < len(raw) and raw[cursor + count] == value and count < 255:
            count += 1
        encoded.extend((count, value))
        cursor += count
    return bytes(encoded)


def decode_rle(encoded: bytes) -> bytes:
    if len(encoded) % 2:
        raise ValueError("RLE stream has an odd byte count")
    decoded = bytearray()
    for index in range(0, len(encoded), 2):
        count, value = encoded[index : index + 2]
        if count == 0:
            raise ValueError("RLE stream contains a zero-length run")
        decoded.extend([value] * count)
    return bytes(decoded)


def cpp_bytes(data: bytes) -> str:
    rows = []
    for start in range(0, len(data), 16):
        chunk = data[start : start + 16]
        rows.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return "\n".join(rows)


def generate(project_root: Path) -> None:
    source_dir = project_root / "assets" / "source"
    include_dir = project_root / "include" / "generated"
    cpp_dir = project_root / "src" / "generated"
    include_dir.mkdir(parents=True, exist_ok=True)
    cpp_dir.mkdir(parents=True, exist_ok=True)

    generated = []
    for spec in ASSETS:
        black, red = image_to_planes(source_dir / spec.filename)
        black_rle = encode_rle(black)
        red_rle = encode_rle(red)
        if decode_rle(black_rle) != black or decode_rle(red_rle) != red:
            raise AssertionError(f"{spec.filename}: RLE round-trip failed")
        generated.append((spec, black, red, black_rle, red_rle))

    header_lines = [
        "#pragma once",
        "",
        '#include "frame_asset.h"',
        "",
        "namespace inkdash::assets {",
        "",
    ]
    for spec, *_ in generated:
        header_lines.append(f"extern const FrameAsset k{spec.symbol};")
    header_lines.extend(["", "}  // namespace inkdash::assets", ""])
    (include_dir / "frame_assets.h").write_text("\n".join(header_lines), encoding="utf-8")

    cpp_lines = [
        "// Generated by tools/generate_frame_assets.py. Do not edit by hand.",
        "#include <Arduino.h>",
        "",
        '#include "generated/frame_assets.h"',
        "",
        "namespace inkdash::assets {",
        "",
    ]
    for spec, black, red, black_rle, red_rle in generated:
        cpp_lines.extend(
            [
                f"const uint8_t k{spec.symbol}BlackRle[] PROGMEM = {{",
                cpp_bytes(black_rle),
                "};",
                "",
                f"const uint8_t k{spec.symbol}RedRle[] PROGMEM = {{",
                cpp_bytes(red_rle),
                "};",
                "",
                f"const FrameAsset k{spec.symbol} = {{",
                f'    "{spec.frame_id}",',
                f"    {WIDTH},",
                f"    {HEIGHT},",
                f"    {{k{spec.symbol}BlackRle, sizeof(k{spec.symbol}BlackRle), {len(black)}, 0x{zlib.crc32(black):08X}u}},",
                f"    {{k{spec.symbol}RedRle, sizeof(k{spec.symbol}RedRle), {len(red)}, 0x{zlib.crc32(red):08X}u}},",
                "};",
                "",
            ]
        )
        print(
            f"{spec.frame_id}: raw={len(black) + len(red):,} bytes, "
            f"rle={len(black_rle) + len(red_rle):,} bytes"
        )
    cpp_lines.extend(["}  // namespace inkdash::assets", ""])
    (cpp_dir / "frame_assets.cpp").write_text("\n".join(cpp_lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="ESP32 project root (defaults to the parent of tools/)",
    )
    args = parser.parse_args()
    generate(args.project_root.resolve())


if __name__ == "__main__":
    main()
